[package]
name = "cuckoo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
gxhash = "3.4.1"
hex = "0.4.3"
rapidhash = "1.1.0"
serde = "1.0.213"
